version: '3'

services:
  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
  nginx:
    image: nginx
    container_name: 'nginx2'
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
